org_types:
  corporation: Corporations
  non-profit:  Non Profits
  university:  Universities
  gov:         Governments
  other:       Other organisations

countries:
  - Australia
  - Belgium
  - Bulgaria
  - Canada
  - Estonia
  - Germany
  - Hungary
  - India
  - Israel
  - Italy
  - Japan
  - Korea
  - Kurdistan
  - New Zealand
  - Philippines
  - Singapore
  - Sri Lanka
  - Sweden
  - Switzerland
  - Taiwan
  - UK
  - USA

